config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'boards/map'

  get 'boards/guardar_map'

  
  

      devise_for :users, controllers: {
        sessions: 'users/sessions', 
        registrations: 'users/registrations'
      }
    

  

  resources :boards do
    resources :posts do
      resources :comments
    end
  end
  

  root 'boards#map'

end

app/models/board.rb
class Board < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	belongs_to :city
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index

    @boards = Board.all

    
      if params[:countr].present?      
        @boards = @boards.joins(:city).where("cities.country_id": params[:countr].to_i)
      end
       
     
     @country_arreglo = Country.all.map{|c| [c.name,c.id]}

  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    if params[:categoria].present?

      @categoria = params[:categoria].to_i
      if params[:categoria].to_i==0
     @posts = @board.posts 
      else
      @posts = @board.posts.where(category_id: params[:categoria].to_i)
      end
       
     else
       @posts = @board.posts 
     end

    @category = Category.all

    @categoria_arreglo = Category.all.map{|c| [c.name,c.id]}
    @categoria_arreglo.push(["Todos",0])
    @board = Board.find(params[:id])
   
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  def categories
    


  end

  def get_address
 @address = Geocoder.address([params[:latitude], params[:longitude]])
 render json: @address
 end


  def map
    @users = User.all
    @markers = Gmaps4rails.build_markers(@users) do |
    user, marker|
     marker.lat user.latitude
     marker.lng user.longitude
    end
    

  end



  def guardar_map

    if params[:param1].present?

      current_user.latitude = params[:param1]

      current_user.longitude = params[:param2]
      current_user.save

    end

    respond_to do |format|

      format.js
    end



  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.fetch(:board, {})
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/guardar_map.js.erb
alert("guardado");

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <div class="catselect">
  
<%= form_tag("",method: "get")  do | f | %>

<%= select_tag :countr, options_for_select(@country_arreglo), class:'form-control' %>
<%= submit_tag "filter", class: 'btn btn-default' %>
<% end %>

</div>

    <% @boards.each do |board| %>
      <ul class="list-group">
        <li class="list-group-item"><%= board.names %>

       <%= link_to 'Show', board, class: "btn" %>
      

       </li>
       
      </ul>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/map.html.erb
<style>
#map {height: 400px;
}

 </style>

<div id="map"></div>
    <script>var handler = Gmaps.build('Google');
handler.buildMap({
    internal: {id: "map"},
    provider: {
        backgroundColor: "black",
        center: new google.maps.LatLng(-33, -70.6)
    }}, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
    });
      
    </script>



<!--<script>
var x = document.getElementById("map");
function getLocation() {
 if (navigator.geolocation) {
 navigator.geolocation.getCurrentPosition(showPosition);
 } else {
 x.innerHTML = "Geolocation is not supported by this browser.";
 }
}
function showPosition(position) {
 x.innerHTML = "Latitude: " + position.coords.latitude +
 "<br>Longitude: " + position.coords.longitude;
 var latitude = position.coords.latitude
 var longitude = position.coords.longitude


  $.ajax({
  url: '<%= boards_guardar_map_path %>',
  type: 'GET',
  dataType: 'script',
  data: {param1: latitude, param2: longitude},
  })

}
-->

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p><br>

<div class="catselect">
<%= link_to 'New Post', new_board_post_path(@board.id) %>
	
<%= form_tag("",method: "get")  do | f | %>

<%= select_tag :categoria, options_for_select(@categoria_arreglo), class:'form-control' %>
<%= submit_tag "filter", class: 'btn btn-default' %>
<% end %>

</div>

<% @posts.each do |p|  %>
	

	<div class="col-md-4">
	<div class="postshow">
		

	<h2 class="title"><%= p.title  %></h2> 
	<p class="cat"><%= p.date  %></p> 
	<p class="cat"> <%= p.category.try(:name)  %> </p>
	<h3 class="body"> <%= p.content  %> </h3>
	<%= link_to 'show', board_post_path(@board.id, p.id)%>


	</div>
	</div>


	
<% end  %>