config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'boards/map'

  get 'boards/guardar_map'

  
  

      devise_for :users, controllers: {
        sessions: 'users/sessions', 
        registrations: 'users/registrations'
      }
    

  

  resources :boards do
    resources :posts do
      resources :comments
    end
  end
  

  root 'boards#map'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :board
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :user, presence: true
  scope :nationality, -> (nationality) { joins(user: :nationality).where('nationalities.name = ?', nationality) }

  def nationality
  	user.nationality
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.nationality(current_user.nationality.name)

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
   
  end

  # GET /posts/new
  def new
    @post = Post.new
    @cat = Category.all
    @board = Board.find(params[:board_id])

  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @board = Board.find(params[:board_id])
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @board, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :date, :category_id, :board_id, :user_id, :comment)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@board, @post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  

  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, Category.all.collect{|c| [c.name, c.id]} %>
  </div>

  <div class="field">
    <%= f.label :board_id %><br>
    <%= f.select :board_id, Board.all.collect{|b| [b.names, b.id]} %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th> 
      <th>Content</th> 
      <th>Date</th>
      <th>Category</th>
      <th>Board</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= current_user %>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.date %></td>
        <td><%= post.category.try :name %></td>
        <td><%= post.board.try :names %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', board_post_path(post.board, post) %></td>
        <td><%= link_to 'Edit', edit_board_post_path(post.board, post) %></td>
        <td><%= link_to 'Destroy', board_post_path(post.id, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_board_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', board_posts_path(@board) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  
    <div class="col-md-4">
      <div class="postshow">
        <p>
          <strong>Title:</strong>
          <%= @post.title %>
        </p>

        <p>
          <strong>Content:</strong>
          <%= @post.content %>
        </p>

        <p>
          <strong>Date:</strong>
          <%= @post.date %>
        </p>

        <p>
          <strong>Category:</strong>
          <%= @post.category.name %>
        </p>

        <p>
          <strong>Board:</strong>
          <%= @post.board.names %>
        </p>



        <p>
          <strong>User:</strong>
          <%= @post.user.email %>
        </p>
    <%=form_for [@post.board, @post, @post.comments.build] do |f| %>
      <%= f.text_area :content %>
      <%= f.button :submit %>
        <p>

      </div>
    </div>


</div>
      
      <% @post.comments.all.each do |c| %>
    <div row>
        <div class="comments col-md-4" >      
         <p>
          <%= c.user.try(:email) %>
          <%= c.content %>
         </p>
        </div>
    </div> 
      <% end %>
    </p>
<% end %>


 <%= link_to 'Back', board_path(@post.board.id) %>
  